SPOOL E:\V10\V10DATOS\LOG\CARGAALBARANGAMBASTAR.LOG APPEND
SET serveroutput ON
SET LINESIZE 200
DECLARE
   V_DIRECTORIO VARCHAR2(50);
   V_PATRON VARCHAR2(50);
   verror_code NUMBER := 0;
   verror_message NVARCHAR := '';
BEGIN
   --SE PROGRAMAN LOS PARAMETROS 
   VDCASERFRY_ALBARAN_DEMANDA.V10_CARGA_DATOS_DEMANDA(verror_code IN OUT NUMBER, verror_message IN OUT VARCHAR2)	   
   COMMIT; 
END;
/
SET serveroutput OFF
SPOOL OFF
/
EXIT;
/
